In [1]:
#read .csv file

#import Libraries
import pandas as pd
import numpy as np


In [2]:
#read CSV file
df = pd.read_csv("./haberman.csv")

In [3]:
print(df)

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]


In [4]:
# to give head of DF
# give first five rows of df
df.head()

30  64   1  1.1
0  30  62   3    1
1  30  65   0    1
2  31  59   2    1
3  31  65   4    1
4  33  58  10    1

In [5]:
#give last few rows
df.tail()

30  64  1  1.1
300  75  62  1    1
301  76  67  0    1
302  77  65  3    1
303  78  65  1    2
304  83  58  2    2

In [6]:
#data slicing
df[2:5]

30  64   1  1.1
2  31  59   2    1
3  31  65   4    1
4  33  58  10    1

In [7]:
#listof columns
df.columns

Index(['30', '64', '1', '1.1'], dtype='object')

In [8]:
#describe min max 
df['30'].min()
df['30'].max()
df['30'].describe()

count    305.000000
mean      52.531148
std       10.744024
min       30.000000
25%       44.000000
50%       52.000000
75%       61.000000
max       83.000000
Name: 30, dtype: float64

In [9]:
#numpy arrays
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
#show dimension
a.ndim

1

In [11]:
#show shape
a.shape

(10,)

In [12]:
#arange with stepsize
a = np.arange(1,10,2)

In [13]:
print(a)

[1 3 5 7 9]


In [14]:
#linspace: divide the range in number of parts
a =np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [15]:
#make a matrix
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#make a identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# make identity matrix with rows and columns
a =np.eye(2,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]]


In [18]:
#make matrix with diagonal values
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
# assigning values in matrix
a[2,1] = 5

In [20]:
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 5 3 0]
 [0 0 0 4]]


In [21]:
#slicing a range
a = np.arange(10)
print(a[1:8:2])

[1 3 5 7]


In [22]:
#functions

#arbitrary arguments:
def arbitrary_arguments():
    return "sometimes we do not know in advance the no. of arguments that will be passed into a function. Python allows us to handle this kind of situation through dfunciton calls with arbitraty no. of arguments"


In [23]:
arbitrary_arguments()

'sometimes we do not know in advance the no. of arguments that will be passed into a function. Python allows us to handle this kind of situation through dfunciton calls with arbitraty no. of arguments'

In [24]:
# text wrap funciton
import textwrap
def text_wrap(string,max_width):
    new_text = textwrap.fill(string,width = max_width)
    return new_text

In [25]:
text_wrap('abcdefghijklmnopqrstuvwxyz',5)

'abcde\nfghij\nklmno\npqrst\nuvwxy\nz'

In [26]:
#list and list functions
emptylist = []

In [27]:
emptylist = ['one','two','three']

In [28]:
print(emptylist)

['one', 'two', 'three']


In [29]:
b = emptylist

In [30]:
print(b)

['one', 'two', 'three']


In [31]:
print(len(b)) #length of list

3


In [32]:
b.append('five') #to add element in the list
print(b)

['one', 'two', 'three', 'five']


In [33]:
# to insert element at certain locations
b.insert(2,'six')
print(b)

['one', 'two', 'six', 'three', 'five']


In [34]:
#to remove element form list
b.remove('six')
print(b)      #remove the first occurence of item

['one', 'two', 'three', 'five']


In [35]:
#to extend the list
c = [1,2,3]
b.extend(c)
print(b)

['one', 'two', 'three', 'five', 1, 2, 3]


In [36]:
#to append the list
b.append(c)
print(b)        #list will be appended as it is in another list

['one', 'two', 'three', 'five', 1, 2, 3, [1, 2, 3]]


In [37]:
# to delete items from list
del b[-1]
print(b)     #delete the specific position

['one', 'two', 'three', 'five', 1, 2, 3]


In [38]:
# to delete items from list
e = b.pop(-1)
print(b)
print(e)

['one', 'two', 'three', 'five', 1, 2]
3


In [39]:
#arrays


In [40]:
#List and Dictionary Comprehension
def list_dictionary_comprehension():
    return "Python comprehensios are syntactic constructs providing a way to build a list, dictionary or set based on the existing list, dictionary or set whilst altering or filtering elements e.g [i for i in range(10,60) if i %10 == 0], insimple words declaring list in one line"

In [41]:
list_dictionary_comprehension()

'Python comprehensios are syntactic constructs providing a way to build a list, dictionary or set based on the existing list, dictionary or set whilst altering or filtering elements e.g [i for i in range(10,60) if i %10 == 0], insimple words declaring list in one line'

In [42]:
#Generators and Decorators
def generators():
    return "It is a function returning an iterable or object over which can iterate that is by taking one value at a time"

In [43]:
def decorator():
    return "A decorator allows us to modify or alter the functions, methods and classes"

In [44]:
# difference between 'is' and '=='
def difference_between_is_and_equal():
    return """ '==' checks for equality b/w the variable and 'is' check for identity of the variables
    """ 

In [45]:
difference_between_is_and_equal()

" '==' checks for equality b/w the variable and 'is' check for identity of the variables\n    "

In [46]:
# differenc e between indexing and slicing
def indexing_and_slicing():
    return """ indexing: extracting or looking one or particular values in a data structure e.g. a = [Python] print(a[2]) = t
    slicing: retreive a sequence of elements e.g. print(a[2:]) = thon
    
    """

In [47]:
indexing_and_slicing()

' indexing: extracting or looking one or particular values in a data structure e.g. a = [Python] print(a[2]) = t\n    slicing: retreive a sequence of elements e.g. print(a[2:]) = thon\n    \n    '

In [48]:
def Python():
    return "python is an object-oriented language, meaning it can encloses the code within objects"

In [49]:
def PEP8():
    return """PEP8 is coding convention, It consists of coding guidelines that are a set of recommendation for python language about making the python more readable
     and usable for another persion"""

In [50]:
def Mutable_and_immutable_objects():
    return """mutability: is the ability to change the portion of data structure without having to recreate it.
    e.g. list,sets,values in the dictionary
    immutability: e.g. integers, string, float, bool, tuples, keys 
    """

In [51]:
Mutable_and_immutable_objects()

'mutability: is the ability to change the portion of data structure without having to recreate it.\n    e.g. list,sets,values in the dictionary\n    immutability: e.g. integers, string, float, bool, tuples, keys \n    '

In [52]:
def compound_data_types():
    return " the data types that is constructed using simple, primitive and basic data types are compound data types"

In [53]:
def data_structure():
    return " DS in python allows us to store multiple observations. these are lists, tuples, sets, and dictionaries"

In [54]:
def difference_between_lists_and_tuplesS():
    return """List: lists are enclosed within []
    Lists are mutable
    Lists are slower than tuples
    Tuples: enclosed withing parenthesis()
    tuples are immutables
    tuples are faster than lists
    tuples must be used where order of the element of the sequence matters
    """

In [57]:
a=[1,5,8,7,5,10]
print(type(a))


<class 'list'>


In [63]:
a.append(11)
print(a)

[1, 5, 10, 8, 7, 5, 10, 11, 11, 11, 11]


In [64]:
a.insert(2,10) #insert(location,value)

In [62]:
print(a)

[1, 5, 10, 8, 7, 5, 10, 11, 11, 11]


In [69]:
#remove
a.remove(10) #remove only removes the first occurence of elements

In [70]:
print(a)

[1, 5, 8, 7, 5, 11, 11, 11, 11]


In [75]:
#pop() -- removes element from the end oof list, return the value
a.pop()
# print(a)

11

In [77]:
a.pop(4) #pop()index -- return the value deleted

5

In [78]:
print(a)

[1, 5, 8, 7]


In [79]:
#two list add ,join , append
b=[4,5,6]
print(a+b)

[1, 5, 8, 7, 4, 5, 6]


In [80]:
a.append(b)

In [81]:
print(a)

[1, 5, 8, 7, [4, 5, 6]]


In [83]:
a.extend(b) #extend is similar to a+b
print(a)

[1, 5, 8, 7, [4, 5, 6], 4, 5, 6, 4, 5, 6]


In [114]:
a.join(b)
print(a)

NameError: name 'join' is not defined

In [85]:
a.insert(2,b)
print(a)

[1, 5, [4, 5, 6], 8, 7, [4, 5, 6], 4, 5, 6, 4, 5, 6]


In [90]:
#delete
del a[2]
print(a)

[1, 5, 5, 6, 4, 5, 6]


In [91]:
a.clear()
print(a)

[]


In [92]:
a=b
print(a)

[4, 5, 6]


In [95]:
a.clear()
a

[]

In [96]:
a=b.copy()
print(a)


[4, 5, 6]


In [99]:
a.append([11,12,13,14])

In [106]:
a.extend(b)

In [108]:
a


[4,
 5,
 6,
 11,
 [11, 12, 13, 14],
 [4, 5, 6],
 [4, 5, 6, 11, [11, 12, 13, 14], [4, 5, 6], 4, 5, 6],
 4,
 5,
 6]

In [109]:
a.count(4)

2

In [111]:
len(a)

10

In [112]:
#slicing
a[2:5]  #starts from the index of first element(n) to (n-1)before last elements 

[6, 11, [11, 12, 13, 14]]

In [113]:
a[2:]  #starts from the index of first element to the last element

[6,
 11,
 [11, 12, 13, 14],
 [4, 5, 6],
 [4, 5, 6, 11, [11, 12, 13, 14], [4, 5, 6], 4, 5, 6],
 4,
 5,
 6]

In [116]:
a


[4,
 5,
 6,
 11,
 [11, 12, 13, 14],
 [4, 5, 6],
 [4, 5, 6, 11, [11, 12, 13, 14], [4, 5, 6], 4, 5, 6],
 4,
 5,
 6]

In [118]:
a[:-3] #slice from right end

[4,
 5,
 6,
 11,
 [11, 12, 13, 14],
 [4, 5, 6],
 [4, 5, 6, 11, [11, 12, 13, 14], [4, 5, 6], 4, 5, 6]]

In [119]:
a.reverse()

In [120]:
a

[6,
 5,
 4,
 [4, 5, 6, 11, [11, 12, 13, 14], [4, 5, 6], 4, 5, 6],
 [4, 5, 6],
 [11, 12, 13, 14],
 11,
 6,
 5,
 4]

In [121]:
a.sort()

TypeError: '<' not supported between instances of 'list' and 'int'

In [122]:
del a[3:6]

In [123]:
a

[6, 5, 4, 11, 6, 5, 4]

In [124]:
a.sort()

In [125]:
a

[4, 4, 5, 5, 6, 6, 11]

In [127]:
a.sort(reverse=True)

In [128]:
a

[11, 6, 6, 5, 5, 4, 4]

In [129]:
c = ['aadrdenv','abalone','alone','acme','add'] #sorting for strings

In [130]:
c.sort(key=len)

In [131]:
c

['add', 'acme', 'alone', 'abalone', 'aadrdenv']

In [132]:
c.index('acme')

1

In [133]:
#list looping
for  i in c:
    print(i)

add
acme
alone
abalone
aadrdenv
