In [1]:
#read .csv file

#import Libraries
import pandas as pd
import numpy as np


In [4]:
#read CSV file
df = pd.read_csv("./haberman.csv")

In [6]:
print(df)

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]


In [9]:
# to give head of DF
# give first five rows of df
df.head()

30  64   1  1.1
0  30  62   3    1
1  30  65   0    1
2  31  59   2    1
3  31  65   4    1
4  33  58  10    1

In [10]:
#give last few rows
df.tail()

30  64  1  1.1
300  75  62  1    1
301  76  67  0    1
302  77  65  3    1
303  78  65  1    2
304  83  58  2    2

In [12]:
#data slicing
df[2:5]

30  64   1  1.1
2  31  59   2    1
3  31  65   4    1
4  33  58  10    1

In [14]:
#listof columns
df.columns

Index(['30', '64', '1', '1.1'], dtype='object')

In [17]:
#describe min max 
df['30'].min()
df['30'].max()
df['30'].describe()

count    305.000000
mean      52.531148
std       10.744024
min       30.000000
25%       44.000000
50%       52.000000
75%       61.000000
max       83.000000
Name: 30, dtype: float64

In [19]:
#numpy arrays
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
#show dimension
a.ndim

1

In [22]:
#show shape
a.shape

(10,)

In [23]:
#arange with stepsize
a = np.arange(1,10,2)

In [24]:
print(a)

[1 3 5 7 9]


In [28]:
#linspace: divide the range in number of parts
a =np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [32]:
#make a matrix
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
#make a identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# make identity matrix with rows and columns
a =np.eye(2,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]]


In [35]:
#make matrix with diagonal values
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [36]:
# assigning values in matrix
a[2,1] = 5

In [37]:
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 5 3 0]
 [0 0 0 4]]


In [39]:
#slicing a range
a = np.arange(10)
print(a[1:8:2])

[1 3 5 7]


In [41]:
#functions

#arbitrary arguments:
def arbitrary_arguments():
    return "sometimes we do not know in advance the no. of arguments that will be passed into a function. Python allows us to handle this kind of situation through dfunciton calls with arbitraty no. of arguments"


In [42]:
arbitrary_arguments()

'sometimes we do not know in advance the no. of arguments that will be passed into a function. Python allows us to handle this kind of situation through dfunciton calls with arbitraty no. of arguments'

In [43]:
# text wrap funciton
import textwrap
def text_wrap(string,max_width):
    new_text = textwrap.fill(string,width = max_width)
    return new_text

In [44]:
text_wrap('abcdefghijklmnopqrstuvwxyz',5)

'abcde\nfghij\nklmno\npqrst\nuvwxy\nz'

In [45]:
#list and list functions
emptylist = []

In [46]:
emptylist = ['one','two','three']

In [47]:
print(emptylist)

['one', 'two', 'three']


In [48]:
b = emptylist

In [49]:
print(b)

['one', 'two', 'three']


In [51]:
print(len(b)) #length of list

3


In [54]:
b.append('five') #to add element in the list
print(b)

['one', 'two', 'three', 'five', 'five', 'five']


In [56]:
# to insert element at certain locations
b.insert(2,'six')
print(b)

['one', 'two', 'six', 'six', 'three', 'five', 'five', 'five']


In [57]:
#to remove element form list
b.remove('six')
print(b)      #remove the first occurence of item

['one', 'two', 'six', 'three', 'five', 'five', 'five']


In [58]:
#to extend the list
c = [1,2,3]
b.extend(c)
print(b)

['one', 'two', 'six', 'three', 'five', 'five', 'five', 1, 2, 3]


In [61]:
#to append the list
b.append(c)
print(b)        #list will be appended as it is in another list

['one', 'two', 'six', 'three', 'five', 'five', 'five', 1, 2, 3, [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [62]:
# to delete items from list
del b[-1]
print(b)     #delete the specific position

['one', 'two', 'six', 'three', 'five', 'five', 'five', 1, 2, 3, [1, 2, 3], [1, 2, 3]]


In [64]:
# to delete items from list
e = b.pop(-1)
print(b)
print(e)

['one', 'two', 'six', 'three', 'five', 'five', 'five', 1, 2, 3]
[1, 2, 3]


In [ ]:
#coderbyte
stringtaken = "nzvf2bo6j7"
conca = 